from crewai import Agent, Task, Crew, Process
from crewai.project import CrewBase, agent, task
from config.llm import gemini_llm
from pathlib import Path
from pydantic import (
    BaseModel, Field, 
    model_validator, field_validator
)
from typing import List, Optional, Annotated
from functions.log_adder import add_log

CURRENT_DIR = Path(__file__).parent

# Annotated field validations for cleaner schema evaluation tracking
ValidPage = Annotated[int, Field(default=0, ge=0)]
ValidYear = Annotated[str, Field(default="9999", pattern=r"^\d{4}$")]
CompanyName = Annotated[str, Field(default="unknown_company", max_length=20, description="A short name for the company derived from the pdf")]


class PageRange(BaseModel):
    """Represents the starting and ending printed page bounds for a structural financial document.

    Typically extracted from the document Table of Contents (TOC). Default values cascade
    safely down to 0 if no structural directory headers are visible in the document canvas.
    """
    start_page: ValidPage = Field(description="The starting printed page number")
    end_page: ValidPage = Field(description="The ending printed page number")
    
    @model_validator(mode="after")
    def validate_page_order(self) -> 'PageRange':
        """Validates that document bounds are ordered sequentially.

        Returns:
            PageRange: The verified configuration instance.

        Raises:
            ValueError: If the end boundary index precedes the start boundary index.
        """
        if self.end_page < self.start_page:
            add_log(f"Validation rejection: end_page ({self.end_page}) precedes start_page ({self.start_page})", level='warning', source='PAGE_DETECTION')
            raise ValueError(f"Invalid page order!\nend_page {self.end_page} cannot be less than start_page {self.start_page}")
        return self
    

class FinancialStatementPages(BaseModel):
    """Pydantic structural envelope tracking isolated ranges for each corporate statement type."""
    balance_sheet: PageRange | None = None
    income_statement: PageRange | None = None
    cash_flow: PageRange | None = None
    changes_in_equity: PageRange | None = None


class PageDetectionOutput(BaseModel):
    """Master structured Pydantic payload returned upon a successful PageDetectionCrew sequence execution."""
    company_name: CompanyName = "unknown_company"
    year: ValidYear = "9999"
    statement_pages: FinancialStatementPages | None = None
    first_numbered_page_physical_index: ValidPage = 0
    
    @field_validator("company_name")
    @classmethod
    def format_company_name(cls, value: str) -> str:
        """Sanitizes raw extracted string segments into clean, filesystem-safe names.

        Args:
            value (str): The raw text segment generated by the modeling engine.

        Returns:
            str: Lowercase, space-stripped string utilizing underscores for spacing.
        """
        return value.strip().replace(" ", "_").lower()


@CrewBase
class PageDetectionCrew:
    """An agentic orchestrator class that targets introductory document texts to extract corporate profiles, 

    reporting periods, and physical page offsets across financial reports.
    """

    agents_config = str(CURRENT_DIR / "config/agents.yaml")
    tasks_config = str(CURRENT_DIR / "config/tasks.yaml")
    
    @agent 
    def page_detection_agent(self) -> Agent:
        """Constructs an analytical agent tailored specifically for structural scanning and indexing text analysis tasks.

        Returns:
            Agent: Configured agent environment paired with target model endpoints.
        """
        add_log("Initializing agent context template for structural page identification routines.", level='debug', source='PAGE_DETECTION')
        return Agent(
            config=self.agents_config["page_detection_agent"],
            verbose=True,
            llm=gemini_llm,
            max_iter=2,
            max_retries=2  # Reinforced retry threshold to tolerate runtime schema backpressure safely
        )
        
    @task
    def page_detection_task(self) -> Task:
        """Defines target objectives and wires up schema processing objects to evaluate document text layers.

        Returns:
            Task: Target runtime task sequence paired with the PageDetectionOutput output layout rules.
        """
        return Task(
            config=self.tasks_config["page_detection_task"],
            agent=self.page_detection_agent(),
            output_pydantic=PageDetectionOutput
        )
    
    def crew(self) -> Crew:
        """Assembles internal processing states and task lists into an agent execution instance.

        Returns:
            Crew: Production multi-agent sequential pipeline execution orchestrator.
        """
        add_log("Compiling components into unified sequential Page Detection execution thread loop.", level='info', source='PAGE_DETECTION')
        return Crew(
            agents=[self.page_detection_agent()],
            tasks=[self.page_detection_task()],
            process=Process.sequential,
            verbose=True
        )
